run:
  skip-dirs:
    - example
linters:
  enable:
    - lll
    - gofmt
    - golint
    - exportloopref
    - unparam

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
